[idris2]
url = "https://github.com/spcfox/Idris2"
commit = "latest:ifunsolved"

[custom.all.typelevel-emptiness-collections]
type = "local"
path = "."
ipkg = "typelevel-emptiness-collections.ipkg"
test = "tests/tests.ipkg"
